version: '3.8'
services:
  my5grantester:
    image: my5grantester:latest
    container_name: my5grantester
    privileged: true
    command: ./app load-test -n 1000
    volumes:
      - ./config/tester.yaml:/workspace/my5G-RANTester/config/config.yml
    cap_add:
      - NET_ADMIN
    networks:
      default:
          ipv4_address: 172.22.0.23
    healthcheck:
      test: /bin/bash -c "ip addr | grep uetun1"
      interval: 10s
      timeout: 5s
      retries: 5
networks:
  default:
    ipam:
      config:
        - subnet: 172.22.0.0/24
#        external:
#            name: docker_open5gs_home_default
