gnodeb:
  controlif:
    ip: "0.0.0.0"
    port: 9487
  dataif:
    ip: "0.0.0.0"
    port: 2152
  plmnlist:
    mcc: "208"
    mnc: "93"
    tac: "000007"
    gnbid: "000003"
  slicesupportlist:
    sst: "01"
    sd: "000001"
  test: "test-normal-registration"
ue:
  msin: "0000000001"
  key: "465B5CE8B199B49FAA5F0A2EE238A6BC"
  opc: "E8ED289DEBA952E4283B54E88E6183CA"
  amf: "8000"
  sqn: "0000000"
  dnn: "internet"
  hplmn:
    mcc: "208"
    mnc: "93"
  snssai:
    sst: 1
    sd: "000001"
  integrity:
    nia0: false
    nia1: false
    nia2: true
  ciphering:
    nea0: true
    nea1: false
    nea2: false
  test: "test-5g-guti"
amfif:
  ip: "172.31.93.235"
  port: 30412
